#pragma once

#define VOLTWISE_UART_RX 16
#define VOLTWISE_UART_TX 17
#define VOLTWISE_BAUD 9600
#define VOLTWISE_MQTT_INTERVAL_MS 500
#define VOLTWISE_PZEM_INTERVAL_MS 100
#define VOLTWISE_WEB_PORT 80

#define VOLTWISE_NET_WAIT_MS 15000
#define VOLTWISE_NET_WAIT_NO_PROFILE_MS 8000
#define VOLTWISE_OFFLINE_BEFORE_AP_MS 10000
#define VOLTWISE_NET_POLL_MS 2000

#define VOLTWISE_AP_PREFIX "VoltWise-Setup-"
#define VOLTWISE_MAX_WIFI_PROFILES 5

#ifndef VOLTWISE_FW_VERSION
#define VOLTWISE_FW_VERSION "0.3.1"
#endif

#ifndef VOLTWISE_BOARD_PROFILE
#define VOLTWISE_BOARD_PROFILE "esp32dev"
#endif

#ifndef VOLTWISE_GITHUB_REPO
#define VOLTWISE_GITHUB_REPO "EvilMonkey09/voltwise-v2"
#endif

#define VOLTWISE_OTA_CHECK_INTERVAL_MS (6UL * 3600UL * 1000UL)
